name: Windows RDP by Cloudflare

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Create User
      run: |
        net user winrdp P@ssw0rd123! /add
        net localgroup administrators winrdp /add

    - name: Download & Start Cloudflare Tunnel
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
        ./cloudflared.exe tunnel --url rdp://localhost:3389 --log-level debug
